name: workflow1
on: 
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: cat /etc/os-release
  job2:
    runs-on: self-hosted
    steps:
      - name: first step
        run: cat /etc/os-release
